before:
  hooks:
    - go mod tidy
dist: release
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Tag }}-source'
checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
builds:
  -
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X "github.com/rancher/yip/cmd.CLIVersion={{ .Tag }}"
      - -X "github.com/rancher/yip/cmd.BuildTime={{ time "2006-01-02 15:04:05 MST" }}"
      - -X "github.com/rancher/yip/cmd.BuildCommit={{ .FullCommit }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
archives:
  - format: binary # this removes the tar of the archives, leaving the binaries alone
    name_template: yip-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
